config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #home
  get '/', to: "home#index"

  #gif_landing_page
  resources :gifs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    begin
      @gif = DoggoService.random_with_type(params[:breed])
      @dog = params[:breed].titleize
    rescue
      flash[:notice] = 'An error occured while finding your gif, please try again'
      redirect_to "/"
    end
  end

  def new
    GifMailer.new_email(params[:gif], params[:email_address]).deliver_now
    flash[:notice] = "Your email has been sent to #{params[:email_address]}!"
    redirect_to "/"

    if params[:email_address].empty?
      flash[:notice] = 'Please enter a valid email address'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dog_list = BreedService.all_breeds
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifs/_email.html.erb
<%= form_with url: new_gif_path, local:true, method: :get do |f| %>

  <%= f.text_field :email_address %>

  <%= f.hidden_field :gif, value: gif %>

  <%= f.submit "Email this gif!", class: "btn btn-info btn-lg" %><br>

<% end%>

app/views/gifs/index.html.erb
<div class="container">
<%= render partial: 'shared/nav' %>
  <center>
    <br><h3>Here is your random <%= @dog %> Gif!</h3><br>
    
    <%= image_tag @gif.image_url %>
    <br><br>
    <h4><%= link_to "Find another Gif", "/" , class: 'find_gif' %></h4>
    <br><br>
    <%= render partial: 'email', locals: { gif: @gif.image_url } %>
  </center>
</div>

app/views/home/_dog_form.html.erb
<%= form_with url: gifs_path, local: true, method: :get do |f|%>

<br><h4><%= f.label 'Select a dog breed!' %></h4>
<%= f.select :breed, (dog_list), selected: dog_list.sample %><br><br>

<%= f.submit "Get a Dog Gif", class: "btn btn-info btn-lg" %>

<% end %>
<br>

app/views/home/index.html.erb
<div class="container">
<%= render partial: 'shared/nav' %>
  <center>
  
    <%= image_tag "rando_small.png", class: 'home_image' %><br>
    <%= render partial: 'dog_form', locals: {dog_list: @dog_list}%>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandoDog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end%>
    
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark rounded">
  <a class="navbar-brand" href="#">
  <%= image_tag "small_logo.png", style: 'height:20vw, width:20vw' %>
    
  <a href="/" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-home"></span> Home
  </a>
  
</nav>